// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createClass, createLesson, createQuestion, createSubject, createVideo, getAllClasses, getAllLessons, getAllLessonsBySubjectId, getAllLessonWithClassSubject, getAllQuestions, getAllSubjectDetails, getAllSubjects, getAllVideos, getAllVideosByLessonId, getAllVideosWithDetail, getVideoWithDetail, type Options } from '../sdk.gen';
import type { CreateClassData, CreateClassResponse, CreateLessonData, CreateLessonResponse, CreateQuestionData, CreateQuestionResponse, CreateSubjectData, CreateSubjectResponse, CreateVideoData, CreateVideoResponse, GetAllClassesData, GetAllClassesResponse, GetAllLessonsBySubjectIdData, GetAllLessonsBySubjectIdResponse, GetAllLessonsData, GetAllLessonsResponse, GetAllLessonWithClassSubjectData, GetAllLessonWithClassSubjectResponse, GetAllQuestionsData, GetAllQuestionsResponse, GetAllSubjectDetailsData, GetAllSubjectDetailsResponse, GetAllSubjectsData, GetAllSubjectsResponse, GetAllVideosByLessonIdData, GetAllVideosByLessonIdResponse, GetAllVideosData, GetAllVideosResponse, GetAllVideosWithDetailData, GetAllVideosWithDetailResponse, GetVideoWithDetailData, GetVideoWithDetailResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllClassesQueryKey = (options?: Options<GetAllClassesData>) => createQueryKey('getAllClasses', options);

export const getAllClassesOptions = (options?: Options<GetAllClassesData>) => queryOptions<GetAllClassesResponse, DefaultError, GetAllClassesResponse, ReturnType<typeof getAllClassesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllClasses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllClassesQueryKey(options)
});

export const createClassMutation = (options?: Partial<Options<CreateClassData>>): UseMutationOptions<CreateClassResponse, DefaultError, Options<CreateClassData>> => {
    const mutationOptions: UseMutationOptions<CreateClassResponse, DefaultError, Options<CreateClassData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createClass({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllLessonWithClassSubjectQueryKey = (options?: Options<GetAllLessonWithClassSubjectData>) => createQueryKey('getAllLessonWithClassSubject', options);

export const getAllLessonWithClassSubjectOptions = (options?: Options<GetAllLessonWithClassSubjectData>) => queryOptions<GetAllLessonWithClassSubjectResponse, DefaultError, GetAllLessonWithClassSubjectResponse, ReturnType<typeof getAllLessonWithClassSubjectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllLessonWithClassSubject({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllLessonWithClassSubjectQueryKey(options)
});

export const getAllVideosWithDetailQueryKey = (options?: Options<GetAllVideosWithDetailData>) => createQueryKey('getAllVideosWithDetail', options);

export const getAllVideosWithDetailOptions = (options?: Options<GetAllVideosWithDetailData>) => queryOptions<GetAllVideosWithDetailResponse, DefaultError, GetAllVideosWithDetailResponse, ReturnType<typeof getAllVideosWithDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllVideosWithDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllVideosWithDetailQueryKey(options)
});

export const getAllLessonsBySubjectIdQueryKey = (options: Options<GetAllLessonsBySubjectIdData>) => createQueryKey('getAllLessonsBySubjectId', options);

/**
 * @deprecated
 */
export const getAllLessonsBySubjectIdOptions = (options: Options<GetAllLessonsBySubjectIdData>) => queryOptions<GetAllLessonsBySubjectIdResponse, DefaultError, GetAllLessonsBySubjectIdResponse, ReturnType<typeof getAllLessonsBySubjectIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllLessonsBySubjectId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllLessonsBySubjectIdQueryKey(options)
});

export const getAllLessonsQueryKey = (options?: Options<GetAllLessonsData>) => createQueryKey('getAllLessons', options);

export const getAllLessonsOptions = (options?: Options<GetAllLessonsData>) => queryOptions<GetAllLessonsResponse, DefaultError, GetAllLessonsResponse, ReturnType<typeof getAllLessonsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllLessons({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllLessonsQueryKey(options)
});

export const createLessonMutation = (options?: Partial<Options<CreateLessonData>>): UseMutationOptions<CreateLessonResponse, DefaultError, Options<CreateLessonData>> => {
    const mutationOptions: UseMutationOptions<CreateLessonResponse, DefaultError, Options<CreateLessonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createLesson({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllQuestionsQueryKey = (options?: Options<GetAllQuestionsData>) => createQueryKey('getAllQuestions', options);

export const getAllQuestionsOptions = (options?: Options<GetAllQuestionsData>) => queryOptions<GetAllQuestionsResponse, DefaultError, GetAllQuestionsResponse, ReturnType<typeof getAllQuestionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllQuestions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllQuestionsQueryKey(options)
});

export const createQuestionMutation = (options?: Partial<Options<CreateQuestionData>>): UseMutationOptions<CreateQuestionResponse, DefaultError, Options<CreateQuestionData>> => {
    const mutationOptions: UseMutationOptions<CreateQuestionResponse, DefaultError, Options<CreateQuestionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createQuestion({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllSubjectsQueryKey = (options?: Options<GetAllSubjectsData>) => createQueryKey('getAllSubjects', options);

export const getAllSubjectsOptions = (options?: Options<GetAllSubjectsData>) => queryOptions<GetAllSubjectsResponse, DefaultError, GetAllSubjectsResponse, ReturnType<typeof getAllSubjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllSubjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllSubjectsQueryKey(options)
});

export const createSubjectMutation = (options?: Partial<Options<CreateSubjectData>>): UseMutationOptions<CreateSubjectResponse, DefaultError, Options<CreateSubjectData>> => {
    const mutationOptions: UseMutationOptions<CreateSubjectResponse, DefaultError, Options<CreateSubjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSubject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllSubjectDetailsQueryKey = (options?: Options<GetAllSubjectDetailsData>) => createQueryKey('getAllSubjectDetails', options);

export const getAllSubjectDetailsOptions = (options?: Options<GetAllSubjectDetailsData>) => queryOptions<GetAllSubjectDetailsResponse, DefaultError, GetAllSubjectDetailsResponse, ReturnType<typeof getAllSubjectDetailsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllSubjectDetails({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllSubjectDetailsQueryKey(options)
});

export const getAllVideosByLessonIdQueryKey = (options: Options<GetAllVideosByLessonIdData>) => createQueryKey('getAllVideosByLessonId', options);

/**
 * @deprecated
 */
export const getAllVideosByLessonIdOptions = (options: Options<GetAllVideosByLessonIdData>) => queryOptions<GetAllVideosByLessonIdResponse, DefaultError, GetAllVideosByLessonIdResponse, ReturnType<typeof getAllVideosByLessonIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllVideosByLessonId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllVideosByLessonIdQueryKey(options)
});

export const getAllVideosQueryKey = (options?: Options<GetAllVideosData>) => createQueryKey('getAllVideos', options);

export const getAllVideosOptions = (options?: Options<GetAllVideosData>) => queryOptions<GetAllVideosResponse, DefaultError, GetAllVideosResponse, ReturnType<typeof getAllVideosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllVideos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllVideosQueryKey(options)
});

export const createVideoMutation = (options?: Partial<Options<CreateVideoData>>): UseMutationOptions<CreateVideoResponse, DefaultError, Options<CreateVideoData>> => {
    const mutationOptions: UseMutationOptions<CreateVideoResponse, DefaultError, Options<CreateVideoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createVideo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVideoWithDetailQueryKey = (options: Options<GetVideoWithDetailData>) => createQueryKey('getVideoWithDetail', options);

export const getVideoWithDetailOptions = (options: Options<GetVideoWithDetailData>) => queryOptions<GetVideoWithDetailResponse, DefaultError, GetVideoWithDetailResponse, ReturnType<typeof getVideoWithDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getVideoWithDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getVideoWithDetailQueryKey(options)
});
