// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateClassData, CreateClassResponses, CreateLessonData, CreateLessonResponses, CreateSubjectData, CreateSubjectResponses, CreateVideoData, CreateVideoResponses, GetAllClassesData, GetAllClassesResponses, GetAllLessonsBySubjectIdData, GetAllLessonsBySubjectIdResponses, GetAllLessonsData, GetAllLessonsResponses, GetAllLessonWithClassSubjectData, GetAllLessonWithClassSubjectResponses, GetAllSubjectDetailsData, GetAllSubjectDetailsResponses, GetAllSubjectsData, GetAllSubjectsResponses, GetAllVideosByLessonIdData, GetAllVideosByLessonIdResponses, GetAllVideosData, GetAllVideosResponses, GetAllVideosWithDetailData, GetAllVideosWithDetailResponses, GetVideoWithDetailData, GetVideoWithDetailResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllClasses = <ThrowOnError extends boolean = false>(options?: Options<GetAllClassesData, ThrowOnError>) => (options?.client ?? client).get<GetAllClassesResponses, unknown, ThrowOnError>({ url: '/api/v1/classes', ...options });

export const createClass = <ThrowOnError extends boolean = false>(options: Options<CreateClassData, ThrowOnError>) => (options.client ?? client).post<CreateClassResponses, unknown, ThrowOnError>({
    url: '/api/v1/classes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllLessonWithClassSubject = <ThrowOnError extends boolean = false>(options?: Options<GetAllLessonWithClassSubjectData, ThrowOnError>) => (options?.client ?? client).get<GetAllLessonWithClassSubjectResponses, unknown, ThrowOnError>({ url: '/api/v1/classes/subjects/lessons', ...options });

export const getAllVideosWithDetail = <ThrowOnError extends boolean = false>(options?: Options<GetAllVideosWithDetailData, ThrowOnError>) => (options?.client ?? client).get<GetAllVideosWithDetailResponses, unknown, ThrowOnError>({ url: '/api/v1/classes/subjects/lessons/videos', ...options });

/**
 * @deprecated
 */
export const getAllLessonsBySubjectId = <ThrowOnError extends boolean = false>(options: Options<GetAllLessonsBySubjectIdData, ThrowOnError>) => (options.client ?? client).get<GetAllLessonsBySubjectIdResponses, unknown, ThrowOnError>({ url: '/api/v1/classes/{classId}/subjects/{subjectId}/lessons', ...options });

export const getAllLessons = <ThrowOnError extends boolean = false>(options?: Options<GetAllLessonsData, ThrowOnError>) => (options?.client ?? client).get<GetAllLessonsResponses, unknown, ThrowOnError>({ url: '/api/v1/lessons', ...options });

export const createLesson = <ThrowOnError extends boolean = false>(options: Options<CreateLessonData, ThrowOnError>) => (options.client ?? client).post<CreateLessonResponses, unknown, ThrowOnError>({
    url: '/api/v1/lessons',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllSubjects = <ThrowOnError extends boolean = false>(options?: Options<GetAllSubjectsData, ThrowOnError>) => (options?.client ?? client).get<GetAllSubjectsResponses, unknown, ThrowOnError>({ url: '/api/v1/subjects', ...options });

export const createSubject = <ThrowOnError extends boolean = false>(options: Options<CreateSubjectData, ThrowOnError>) => (options.client ?? client).post<CreateSubjectResponses, unknown, ThrowOnError>({
    url: '/api/v1/subjects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllSubjectDetails = <ThrowOnError extends boolean = false>(options?: Options<GetAllSubjectDetailsData, ThrowOnError>) => (options?.client ?? client).get<GetAllSubjectDetailsResponses, unknown, ThrowOnError>({ url: '/api/v1/subjects/details', ...options });

/**
 * @deprecated
 */
export const getAllVideosByLessonId = <ThrowOnError extends boolean = false>(options: Options<GetAllVideosByLessonIdData, ThrowOnError>) => (options.client ?? client).get<GetAllVideosByLessonIdResponses, unknown, ThrowOnError>({ url: '/api/v1/subjects/{subjectId}/lessons/{lessonId}/videos', ...options });

export const getAllVideos = <ThrowOnError extends boolean = false>(options?: Options<GetAllVideosData, ThrowOnError>) => (options?.client ?? client).get<GetAllVideosResponses, unknown, ThrowOnError>({ url: '/api/v1/videos', ...options });

export const createVideo = <ThrowOnError extends boolean = false>(options: Options<CreateVideoData, ThrowOnError>) => (options.client ?? client).post<CreateVideoResponses, unknown, ThrowOnError>({
    url: '/api/v1/videos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getVideoWithDetail = <ThrowOnError extends boolean = false>(options: Options<GetVideoWithDetailData, ThrowOnError>) => (options.client ?? client).get<GetVideoWithDetailResponses, unknown, ThrowOnError>({ url: '/api/v1/videos/{videoId}', ...options });
