// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/' | (string & {});
};

export type Class = {
    created_at: string;
    id: number;
    name: string;
    updated_at: string;
};

export type CreateClassReq = {
    name: string;
};

export type CreateClassRes = {
    class: Class;
};

export type CreateLessonReq = {
    subject_id: number;
    title: string;
};

export type CreateLessonRes = {
    lesson: Lesson;
};

export type CreateQuestionReq = {
    question: string;
    subject_id: number;
};

export type CreateQuestionRes = {
    question: Question;
};

export type CreateSubjectReq = {
    class_id: number;
    name: string;
};

export type CreateSubjectRes = {
    subject: Subject;
};

export type CreateVideoReq = {
    description: string;
    file_path: string;
    lesson_id: number;
    title: string;
};

export type CreateVideoRes = {
    video: Video;
};

export type GetAllClassesRes = {
    classes: Array<Class>;
};

export type GetAllLessonWithClassSubjectRes = {
    lessons: Array<LessonClassSubject>;
};

export type GetAllLessonsBySubjectIdRes = {
    lessons: Array<Lesson>;
};

export type GetAllLessonsRes = {
    lessons: Array<Lesson>;
};

export type GetAllQuestionsRes = {
    items: Array<QuestionDto>;
};

export type GetAllSubjectDetailsRes = {
    subjects: Array<SubjectDetail>;
};

export type GetAllSubjectsRes = {
    subjects: Array<Subject>;
};

export type GetAllVideosByLessonIdRes = {
    videos: Array<Video>;
};

export type GetAllVideosRes = {
    videos: Array<Video>;
};

export type GetAllVideosWithDetailRes = {
    videos: Array<VideoDetail>;
};

export type GetQuestionRes = {
    question: QuestionDto;
};

export type GetVideoWithDetailRes = {
    video: VideoDetail;
};

export type Lesson = {
    created_at: string;
    id: number;
    subject_id: number;
    title: string;
    updated_at: string;
};

export type LessonClassSubject = {
    class: Class;
    lesson: Lesson;
    subject: Subject;
};

export type LoginReq = {
    email: string;
    password: string;
};

export type LoginRes = {
    user: User;
};

export type LogoutRes = {
    message: string;
};

export type Question = {
    created_at: string;
    id: number;
    question: string;
    subject_id: number;
    updated_at: string;
    user_id: number;
};

export type QuestionDto = {
    class: Class;
    data: Question;
    subject: Subject;
    user: User;
};

export type RegisterReq = {
    email: string;
    name: string;
    password: string;
};

export type RegisterRes = {
    user: User;
};

export type Subject = {
    class_id: number;
    created_at: string;
    id: number;
    name: string;
    updated_at: string;
};

export type SubjectDetail = {
    class: Class;
    subject: Subject;
};

export type User = {
    created_at: string;
    email: string;
    id: number;
    name: string;
    password: string;
    role: string;
    updated_at: string;
};

export type Video = {
    created_at: string;
    description: string;
    file_path: string;
    id: number;
    lesson_id: number;
    title: string;
    updated_at: string;
};

export type VideoDetail = {
    class: Class;
    lesson: Lesson;
    subject: Subject;
    video: Video;
};

export type LoginData = {
    /**
     * body
     */
    body: LoginReq;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginRes;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: LogoutRes;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RegisterData = {
    /**
     * body
     */
    body: RegisterReq;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: RegisterRes;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetAllClassesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/classes';
};

export type GetAllClassesResponses = {
    /**
     * OK
     */
    200: GetAllClassesRes;
};

export type GetAllClassesResponse = GetAllClassesResponses[keyof GetAllClassesResponses];

export type CreateClassData = {
    /**
     * body
     */
    body: CreateClassReq;
    path?: never;
    query?: never;
    url: '/api/v1/classes';
};

export type CreateClassResponses = {
    /**
     * OK
     */
    200: CreateClassRes;
};

export type CreateClassResponse = CreateClassResponses[keyof CreateClassResponses];

export type GetAllLessonWithClassSubjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/classes/subjects/lessons';
};

export type GetAllLessonWithClassSubjectResponses = {
    /**
     * OK
     */
    200: GetAllLessonWithClassSubjectRes;
};

export type GetAllLessonWithClassSubjectResponse = GetAllLessonWithClassSubjectResponses[keyof GetAllLessonWithClassSubjectResponses];

export type GetAllVideosWithDetailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/classes/subjects/lessons/videos';
};

export type GetAllVideosWithDetailResponses = {
    /**
     * OK
     */
    200: GetAllVideosWithDetailRes;
};

export type GetAllVideosWithDetailResponse = GetAllVideosWithDetailResponses[keyof GetAllVideosWithDetailResponses];

export type GetAllLessonsBySubjectIdData = {
    body?: never;
    path: {
        /**
         * classId
         */
        classId: number;
        /**
         * subjectId
         */
        subjectId: number;
    };
    query?: never;
    url: '/api/v1/classes/{classId}/subjects/{subjectId}/lessons';
};

export type GetAllLessonsBySubjectIdResponses = {
    /**
     * OK
     */
    200: GetAllLessonsBySubjectIdRes;
};

export type GetAllLessonsBySubjectIdResponse = GetAllLessonsBySubjectIdResponses[keyof GetAllLessonsBySubjectIdResponses];

export type GetAllLessonsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * classId
         */
        classId?: number;
        /**
         * subjectId
         */
        subjectId?: number;
    };
    url: '/api/v1/lessons';
};

export type GetAllLessonsResponses = {
    /**
     * OK
     */
    200: GetAllLessonsRes;
};

export type GetAllLessonsResponse = GetAllLessonsResponses[keyof GetAllLessonsResponses];

export type CreateLessonData = {
    /**
     * body
     */
    body: CreateLessonReq;
    path?: never;
    query?: never;
    url: '/api/v1/lessons';
};

export type CreateLessonResponses = {
    /**
     * OK
     */
    200: CreateLessonRes;
};

export type CreateLessonResponse = CreateLessonResponses[keyof CreateLessonResponses];

export type GetAllQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * keyword
         */
        keyword?: string;
        /**
         * includes
         */
        includes?: Array<'user' | 'subject' | 'class'>;
    };
    url: '/api/v1/questions';
};

export type GetAllQuestionsResponses = {
    /**
     * OK
     */
    200: GetAllQuestionsRes;
};

export type GetAllQuestionsResponse = GetAllQuestionsResponses[keyof GetAllQuestionsResponses];

export type CreateQuestionData = {
    /**
     * body
     */
    body: CreateQuestionReq;
    path?: never;
    query?: never;
    url: '/api/v1/questions';
};

export type CreateQuestionResponses = {
    /**
     * OK
     */
    200: CreateQuestionRes;
};

export type CreateQuestionResponse = CreateQuestionResponses[keyof CreateQuestionResponses];

export type GetQuestionData = {
    body?: never;
    path: {
        /**
         * questionId
         */
        questionId: number;
    };
    query?: {
        /**
         * includes
         */
        includes?: Array<'user' | 'subject' | 'class'>;
    };
    url: '/api/v1/questions/{questionId}';
};

export type GetQuestionResponses = {
    /**
     * OK
     */
    200: GetQuestionRes;
};

export type GetQuestionResponse = GetQuestionResponses[keyof GetQuestionResponses];

export type GetAllSubjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * classId
         */
        classId?: number;
    };
    url: '/api/v1/subjects';
};

export type GetAllSubjectsResponses = {
    /**
     * OK
     */
    200: GetAllSubjectsRes;
};

export type GetAllSubjectsResponse = GetAllSubjectsResponses[keyof GetAllSubjectsResponses];

export type CreateSubjectData = {
    /**
     * body
     */
    body: CreateSubjectReq;
    path?: never;
    query?: never;
    url: '/api/v1/subjects';
};

export type CreateSubjectResponses = {
    /**
     * OK
     */
    200: CreateSubjectRes;
};

export type CreateSubjectResponse = CreateSubjectResponses[keyof CreateSubjectResponses];

export type GetAllSubjectDetailsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subjects/details';
};

export type GetAllSubjectDetailsResponses = {
    /**
     * OK
     */
    200: GetAllSubjectDetailsRes;
};

export type GetAllSubjectDetailsResponse = GetAllSubjectDetailsResponses[keyof GetAllSubjectDetailsResponses];

export type GetAllVideosByLessonIdData = {
    body?: never;
    path: {
        /**
         * subjectId
         */
        subjectId: number;
        /**
         * lessonId
         */
        lessonId: number;
    };
    query?: never;
    url: '/api/v1/subjects/{subjectId}/lessons/{lessonId}/videos';
};

export type GetAllVideosByLessonIdResponses = {
    /**
     * OK
     */
    200: GetAllVideosByLessonIdRes;
};

export type GetAllVideosByLessonIdResponse = GetAllVideosByLessonIdResponses[keyof GetAllVideosByLessonIdResponses];

export type GetAllVideosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * lessonId
         */
        lessonId?: number;
    };
    url: '/api/v1/videos';
};

export type GetAllVideosResponses = {
    /**
     * OK
     */
    200: GetAllVideosRes;
};

export type GetAllVideosResponse = GetAllVideosResponses[keyof GetAllVideosResponses];

export type CreateVideoData = {
    /**
     * body
     */
    body: CreateVideoReq;
    path?: never;
    query?: never;
    url: '/api/v1/videos';
};

export type CreateVideoResponses = {
    /**
     * OK
     */
    200: CreateVideoRes;
};

export type CreateVideoResponse = CreateVideoResponses[keyof CreateVideoResponses];

export type GetVideoWithDetailData = {
    body?: never;
    path: {
        /**
         * videoId
         */
        videoId: number;
    };
    query?: never;
    url: '/api/v1/videos/{videoId}';
};

export type GetVideoWithDetailResponses = {
    /**
     * OK
     */
    200: GetVideoWithDetailRes;
};

export type GetVideoWithDetailResponse = GetVideoWithDetailResponses[keyof GetVideoWithDetailResponses];
