/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedAuthRouteImport } from './routes/_unauthenticated/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVideoIndexRouteImport } from './routes/_authenticated/admin/video/index'
import { Route as AuthenticatedAdminDataIndexRouteImport } from './routes/_authenticated/admin/data/index'
import { Route as AuthenticatedAdminVideoCreateRouteImport } from './routes/_authenticated/admin/video/create'
import { Route as AuthenticatedSubjectsSubjectIdLessonsIndexRouteImport } from './routes/_authenticated/subjects/$subjectId/lessons/index'
import { Route as AuthenticatedAdminVideoVideoIdIndexRouteImport } from './routes/_authenticated/admin/video/$videoId.index'
import { Route as AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRouteImport } from './routes/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/index'
import { Route as AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRouteImport } from './routes/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/$videoId/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedAuthRoute = UnauthenticatedAuthRouteImport.update({
  id: '/_unauthenticated/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVideoIndexRoute =
  AuthenticatedAdminVideoIndexRouteImport.update({
    id: '/admin/video/',
    path: '/admin/video/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDataIndexRoute =
  AuthenticatedAdminDataIndexRouteImport.update({
    id: '/admin/data/',
    path: '/admin/data/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideoCreateRoute =
  AuthenticatedAdminVideoCreateRouteImport.update({
    id: '/admin/video/create',
    path: '/admin/video/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdLessonsIndexRoute =
  AuthenticatedSubjectsSubjectIdLessonsIndexRouteImport.update({
    id: '/subjects/$subjectId/lessons/',
    path: '/subjects/$subjectId/lessons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideoVideoIdIndexRoute =
  AuthenticatedAdminVideoVideoIdIndexRouteImport.update({
    id: '/admin/video/$videoId/',
    path: '/admin/video/$videoId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute =
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRouteImport.update({
    id: '/subjects/$subjectId/lessons/$lessonId/videos/',
    path: '/subjects/$subjectId/lessons/$lessonId/videos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute =
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRouteImport.update(
    {
      id: '/subjects/$subjectId/lessons/$lessonId/videos/$videoId/',
      path: '/subjects/$subjectId/lessons/$lessonId/videos/$videoId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/test': typeof TestRoute
  '/auth': typeof UnauthenticatedAuthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/video/create': typeof AuthenticatedAdminVideoCreateRoute
  '/admin/data/': typeof AuthenticatedAdminDataIndexRoute
  '/admin/video/': typeof AuthenticatedAdminVideoIndexRoute
  '/admin/video/$videoId/': typeof AuthenticatedAdminVideoVideoIdIndexRoute
  '/subjects/$subjectId/lessons/': typeof AuthenticatedSubjectsSubjectIdLessonsIndexRoute
  '/subjects/$subjectId/lessons/$lessonId/videos/': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute
  '/subjects/$subjectId/lessons/$lessonId/videos/$videoId/': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/auth': typeof UnauthenticatedAuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/video/create': typeof AuthenticatedAdminVideoCreateRoute
  '/admin/data': typeof AuthenticatedAdminDataIndexRoute
  '/admin/video': typeof AuthenticatedAdminVideoIndexRoute
  '/admin/video/$videoId': typeof AuthenticatedAdminVideoVideoIdIndexRoute
  '/subjects/$subjectId/lessons': typeof AuthenticatedSubjectsSubjectIdLessonsIndexRoute
  '/subjects/$subjectId/lessons/$lessonId/videos': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute
  '/subjects/$subjectId/lessons/$lessonId/videos/$videoId': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/test': typeof TestRoute
  '/_unauthenticated/auth': typeof UnauthenticatedAuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/video/create': typeof AuthenticatedAdminVideoCreateRoute
  '/_authenticated/admin/data/': typeof AuthenticatedAdminDataIndexRoute
  '/_authenticated/admin/video/': typeof AuthenticatedAdminVideoIndexRoute
  '/_authenticated/admin/video/$videoId/': typeof AuthenticatedAdminVideoVideoIdIndexRoute
  '/_authenticated/subjects/$subjectId/lessons/': typeof AuthenticatedSubjectsSubjectIdLessonsIndexRoute
  '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute
  '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/$videoId/': typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/auth'
    | '/admin/'
    | '/admin/video/create'
    | '/admin/data/'
    | '/admin/video/'
    | '/admin/video/$videoId/'
    | '/subjects/$subjectId/lessons/'
    | '/subjects/$subjectId/lessons/$lessonId/videos/'
    | '/subjects/$subjectId/lessons/$lessonId/videos/$videoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/auth'
    | '/'
    | '/admin'
    | '/admin/video/create'
    | '/admin/data'
    | '/admin/video'
    | '/admin/video/$videoId'
    | '/subjects/$subjectId/lessons'
    | '/subjects/$subjectId/lessons/$lessonId/videos'
    | '/subjects/$subjectId/lessons/$lessonId/videos/$videoId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/test'
    | '/_unauthenticated/auth'
    | '/_authenticated/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/video/create'
    | '/_authenticated/admin/data/'
    | '/_authenticated/admin/video/'
    | '/_authenticated/admin/video/$videoId/'
    | '/_authenticated/subjects/$subjectId/lessons/'
    | '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/'
    | '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/$videoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  TestRoute: typeof TestRoute
  UnauthenticatedAuthRoute: typeof UnauthenticatedAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/auth': {
      id: '/_unauthenticated/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthenticatedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video/': {
      id: '/_authenticated/admin/video/'
      path: '/admin/video'
      fullPath: '/admin/video/'
      preLoaderRoute: typeof AuthenticatedAdminVideoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/data/': {
      id: '/_authenticated/admin/data/'
      path: '/admin/data'
      fullPath: '/admin/data/'
      preLoaderRoute: typeof AuthenticatedAdminDataIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video/create': {
      id: '/_authenticated/admin/video/create'
      path: '/admin/video/create'
      fullPath: '/admin/video/create'
      preLoaderRoute: typeof AuthenticatedAdminVideoCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$subjectId/lessons/': {
      id: '/_authenticated/subjects/$subjectId/lessons/'
      path: '/subjects/$subjectId/lessons'
      fullPath: '/subjects/$subjectId/lessons/'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video/$videoId/': {
      id: '/_authenticated/admin/video/$videoId/'
      path: '/admin/video/$videoId'
      fullPath: '/admin/video/$videoId/'
      preLoaderRoute: typeof AuthenticatedAdminVideoVideoIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/': {
      id: '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/'
      path: '/subjects/$subjectId/lessons/$lessonId/videos'
      fullPath: '/subjects/$subjectId/lessons/$lessonId/videos/'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/$videoId/': {
      id: '/_authenticated/subjects/$subjectId/lessons/$lessonId/videos/$videoId/'
      path: '/subjects/$subjectId/lessons/$lessonId/videos/$videoId'
      fullPath: '/subjects/$subjectId/lessons/$lessonId/videos/$videoId/'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminVideoCreateRoute: typeof AuthenticatedAdminVideoCreateRoute
  AuthenticatedAdminDataIndexRoute: typeof AuthenticatedAdminDataIndexRoute
  AuthenticatedAdminVideoIndexRoute: typeof AuthenticatedAdminVideoIndexRoute
  AuthenticatedAdminVideoVideoIdIndexRoute: typeof AuthenticatedAdminVideoVideoIdIndexRoute
  AuthenticatedSubjectsSubjectIdLessonsIndexRoute: typeof AuthenticatedSubjectsSubjectIdLessonsIndexRoute
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute: typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute: typeof AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminVideoCreateRoute: AuthenticatedAdminVideoCreateRoute,
  AuthenticatedAdminDataIndexRoute: AuthenticatedAdminDataIndexRoute,
  AuthenticatedAdminVideoIndexRoute: AuthenticatedAdminVideoIndexRoute,
  AuthenticatedAdminVideoVideoIdIndexRoute:
    AuthenticatedAdminVideoVideoIdIndexRoute,
  AuthenticatedSubjectsSubjectIdLessonsIndexRoute:
    AuthenticatedSubjectsSubjectIdLessonsIndexRoute,
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute:
    AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosIndexRoute,
  AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute:
    AuthenticatedSubjectsSubjectIdLessonsLessonIdVideosVideoIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  TestRoute: TestRoute,
  UnauthenticatedAuthRoute: UnauthenticatedAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
